### ISSUE TITLE
Urban SARCA QGIS plugin not running (Python Error)

### ISSUE THREAD

**Issue by ajminer** [JakubBrom/UrbanSARCA#1]
Hi,

I just installed the UrbanSARCA plugin in QGIS 3.16.9 and keep receiving the following message when I try to start the plugin: 

2022-09-06T16:09:38     WARNING    Traceback (most recent call last):
              File "C:\OSGeo4W\apps\Python39\lib\urllib\request.py", line 1346, in do_open
              h.request(req.get_method(), req.selector, req.data, headers,
              File "C:\OSGeo4W\apps\Python39\lib\http\client.py", line 1253, in request
              self._send_request(method, url, body, headers, encode_chunked)
              File "C:\OSGeo4W\apps\Python39\lib\http\client.py", line 1299, in _send_request
              self.endheaders(body, encode_chunked=encode_chunked)
              File "C:\OSGeo4W\apps\Python39\lib\http\client.py", line 1248, in endheaders
              self._send_output(message_body, encode_chunked=encode_chunked)
              File "C:\OSGeo4W\apps\Python39\lib\http\client.py", line 1008, in _send_output
              self.send(msg)
              File "C:\OSGeo4W\apps\Python39\lib\http\client.py", line 948, in send
              self.connect()
              File "C:\OSGeo4W\apps\Python39\lib\http\client.py", line 1422, in connect
              self.sock = self._context.wrap_socket(self.sock,
              File "C:\OSGeo4W\apps\Python39\lib\ssl.py", line 500, in wrap_socket
              return self.sslsocket_class._create(
              File "C:\OSGeo4W\apps\Python39\lib\ssl.py", line 1040, in _create
              self.do_handshake()
              File "C:\OSGeo4W\apps\Python39\lib\ssl.py", line 1309, in do_handshake
              self._sslobj.do_handshake()
             ssl.SSLError: A failure in the SSL library occurred (_ssl.c:1129)
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\Users/Amanda/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UrbanSARCA-master\urban_sarca.py", line 545, in run
              self.showInfo()
              File "C:\Users/Amanda/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\UrbanSARCA-master\urban_sarca.py", line 514, in showInfo
              data = urllib.request.urlopen(icon_path).read()
              File "C:\OSGeo4W\apps\Python39\lib\urllib\request.py", line 214, in urlopen
              return opener.open(url, data, timeout)
              File "C:\OSGeo4W\apps\Python39\lib\urllib\request.py", line 517, in open
              response = self._open(req, data)
              File "C:\OSGeo4W\apps\Python39\lib\urllib\request.py", line 534, in _open
              result = self._call_chain(self.handle_open, protocol, protocol +
              File "C:\OSGeo4W\apps\Python39\lib\urllib\request.py", line 494, in _call_chain
              result = func(*args)
              File "C:\OSGeo4W\apps\Python39\lib\urllib\request.py", line 1389, in https_open
              return self.do_open(http.client.HTTPSConnection, req,
              File "C:\OSGeo4W\apps\Python39\lib\urllib\request.py", line 1349, in do_open
              raise URLError(err)
             urllib.error.URLError:

**Comment by JakubBrom** [comment]
Fixed
